[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]  
include = ["sensingpy*"]
exclude = ["sphinx*", "tests*"]

[project]
name = "sensingpy"
version = "3.0.0"
description = "A Python package for geospatial image processing and analysis."
readme = "README.md"
requires-python = ">=3.11"
license = "GPL-3.0-or-later"
authors = [
    { name = "Aouei", email = "sergiohercar1@gmail.com" }
]

dependencies = [
    'matplotlib', 'numpy', 'xarray', 'rasterio', 'pyproj', 
    'shapely', 'cartopy', 'contextily', 'scipy', 'seaborn'
]

[project.urls]
"Homepage" = "https://github.com/Aouei/sensingpy"
"Bug Tracker" = "https://github.com/Aouei/sensingpy/issues"