name: Release to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Versión a publicar"
        required: true
        default: "v1.0.0"
  push:
    tags:
      - "v*.*.*"   # v1.2.3
permissions:
  contents: read
  id-token: write
  
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necesario para que setuptools-scm vea tags

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build
        run: python -m build

      - name: Publish to PyPI
        uses: __token__
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
